name: build-and-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'  

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download and install geckodriver
        run: |
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
          curl -L "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz" -o geckodriver.tar.gz
          sudo tar -xzf geckodriver.tar.gz -C /usr/local/bin
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Run Tests
        env:
          GECKODRIVER_PATH: /usr/local/bin/geckodriver
        run: mvn test

